server:
  port: 8182
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: MySql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      sort:
        sort-parameter: ordem
      pageable:
        page-parameter: pagina
        size-parameter: tamanho

application:
  security:
    token:
      secret: ${JWT_SECRET:senha}