server:
  port: 8182

spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true